POST http://localhost:3306/items
Content-Type: application/json

{
    
}

###

GET http://localhost:3306/items

###

GET https://shopping-in-cph.herokuapp.com

###

GET http://localhost:3306/items/614e1515627f4eb8477afb1e

###

POST http://localhost:3306/items
Content-Type: application/json

{
    "name": "ananas",
    "check": true,
    "artWorkshop": false    
}

###

POST https://shopping-in-cph.herokuapp.com
Content-Type: application/json

{
    "name": "heroku",
    "checked": true
    
}




###

# PATCH doesn-t work and is replaced by POST

POST http://localhost:3306/items/61508e6bd789cb6afd38b3a4
Content-Type: application/json

{
    
    "check": false
    
}




###

DELETE http://localhost:3306/items/61508acdf726df5e94f7062c